import type { ToolDef, DependencyEdge, GroupConfig, ToolGroup } from "./types.ts";

export const groups: Record<string, GroupConfig> = {
  gmail:                { color: "#EA4335", label: "Gmail" },
  contacts:             { color: "#34A853", label: "Contacts" },
  calendar:             { color: "#4285F4", label: "Calendar" },
  drive:                { color: "#FBBC05", label: "Drive" },
  sheets:               { color: "#0F9D58", label: "Sheets" },
  tasks:                { color: "#FF6D00", label: "Tasks" },
  photos:               { color: "#E91E63", label: "Photos" },
  analytics:            { color: "#9C27B0", label: "Analytics" },
  github_repo:          { color: "#24292E", label: "GitHub: Repos" },
  github_branches:      { color: "#0366D6", label: "GitHub: Branches" },
  github_commits:       { color: "#6A0DAD", label: "GitHub: Commits" },
  github_issues:        { color: "#D73A49", label: "GitHub: Issues" },
  github_prs:           { color: "#6F42C1", label: "GitHub: Pull Requests" },
  github_actions:       { color: "#2188FF", label: "GitHub: Actions" },
  github_deploy:        { color: "#28A745", label: "GitHub: Deployments" },
  github_releases:      { color: "#E36209", label: "GitHub: Releases" },
  github_org:           { color: "#586069", label: "GitHub: Org/Teams" },
  github_collaborators: { color: "#B31D28", label: "GitHub: Collaborators" },
  github_checks:        { color: "#032F62", label: "GitHub: Checks" },
};

export const tools: ToolDef[] = [
  // ─── Gmail ────────────────────────────────────────────────────────────────
  {
    id: "GOOGLESUPER_GMAIL_LIST_THREADS",
    label: "List Threads",
    description: "Retrieve all Gmail conversation threads. Returns thread_id list.",
    group: "gmail",
    provides: ["thread_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_GMAIL_GET_THREAD",
    label: "Get Thread",
    description: "Fetch full details of a single Gmail thread. Requires thread_id.",
    group: "gmail",
    provides: [],
    requires: ["thread_id"],
  },
  {
    id: "GOOGLESUPER_GMAIL_REPLY_TO_THREAD",
    label: "Reply to Thread",
    description: "Send a reply within an existing Gmail thread. Requires thread_id.",
    group: "gmail",
    provides: [],
    requires: ["thread_id"],
  },
  {
    id: "GOOGLESUPER_GMAIL_LIST_MESSAGES",
    label: "List Messages",
    description: "List Gmail messages (with optional query filters). Returns message_ids.",
    group: "gmail",
    provides: ["message_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_GMAIL_GET_MESSAGE",
    label: "Get Message",
    description: "Fetch full content of a specific Gmail message. Requires message_id.",
    group: "gmail",
    provides: [],
    requires: ["message_id"],
  },
  {
    id: "GOOGLESUPER_GMAIL_SEND_EMAIL",
    label: "Send Email",
    description: "Compose and send a new Gmail message. Requires recipient email address.",
    group: "gmail",
    provides: [],
    requires: ["email"],
  },
  {
    id: "GOOGLESUPER_GMAIL_DELETE_MESSAGE",
    label: "Delete Message",
    description: "Permanently delete a Gmail message. Requires message_id.",
    group: "gmail",
    provides: [],
    requires: ["message_id"],
  },
  {
    id: "GOOGLESUPER_GMAIL_LIST_DRAFTS",
    label: "List Drafts",
    description: "List all Gmail drafts. Returns draft_ids.",
    group: "gmail",
    provides: ["draft_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_GMAIL_CREATE_DRAFT",
    label: "Create Draft",
    description: "Create a new Gmail draft message. Returns draft_id.",
    group: "gmail",
    provides: ["draft_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_GMAIL_GET_DRAFT",
    label: "Get Draft",
    description: "Retrieve content of a specific Gmail draft. Requires draft_id.",
    group: "gmail",
    provides: [],
    requires: ["draft_id"],
  },
  {
    id: "GOOGLESUPER_GMAIL_SEND_DRAFT",
    label: "Send Draft",
    description: "Send an existing Gmail draft. Requires draft_id.",
    group: "gmail",
    provides: [],
    requires: ["draft_id"],
  },
  {
    id: "GOOGLESUPER_GMAIL_LIST_LABELS",
    label: "List Labels",
    description: "Retrieve all Gmail labels. Returns label_ids and names.",
    group: "gmail",
    provides: ["label_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_GMAIL_CREATE_LABEL",
    label: "Create Label",
    description: "Create a new Gmail label. Returns label_id.",
    group: "gmail",
    provides: ["label_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_ADD_LABEL_TO_EMAIL",
    label: "Modify Email Labels",
    description: "Add or remove labels on a Gmail message. Requires message_id + label_id.",
    group: "gmail",
    provides: [],
    requires: ["message_id", "label_id"],
  },
  {
    id: "GOOGLESUPER_BATCH_DELETE_MESSAGES",
    label: "Batch Delete Messages",
    description: "Permanently delete multiple Gmail messages. Requires message_ids.",
    group: "gmail",
    provides: [],
    requires: ["message_id"],
  },
  {
    id: "GOOGLESUPER_BATCH_MODIFY_MESSAGES",
    label: "Batch Modify Messages",
    description: "Apply label changes to up to 1000 messages. Requires message_ids + label_ids.",
    group: "gmail",
    provides: [],
    requires: ["message_id", "label_id"],
  },

  // ─── Contacts ─────────────────────────────────────────────────────────────
  {
    id: "GOOGLESUPER_CONTACTS_LIST",
    label: "List Contacts",
    description: "List all Google Contacts. Returns contact names and email addresses.",
    group: "contacts",
    provides: ["email", "contact_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_CONTACTS_SEARCH",
    label: "Search Contacts",
    description: "Search contacts by name or email. Returns matching email addresses. Used to look up email from a person's name.",
    group: "contacts",
    provides: ["email", "contact_id"],
    requires: [],
  },

  // ─── Calendar ─────────────────────────────────────────────────────────────
  {
    id: "GOOGLESUPER_CALENDAR_LIST_LIST",
    label: "List Calendars",
    description: "List all calendars on the user's calendar list. Returns calendar_ids.",
    group: "calendar",
    provides: ["calendar_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_CALENDARS_INSERT",
    label: "Create Calendar",
    description: "Create a new secondary Google Calendar. Returns calendar_id.",
    group: "calendar",
    provides: ["calendar_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_CALENDAR_LIST_GET",
    label: "Get Calendar",
    description: "Retrieve metadata for a specific calendar. Requires calendar_id.",
    group: "calendar",
    provides: [],
    requires: ["calendar_id"],
  },
  {
    id: "GOOGLESUPER_CALENDARS_UPDATE",
    label: "Update Calendar",
    description: "Update calendar metadata (title, timezone, etc.). Requires calendar_id.",
    group: "calendar",
    provides: [],
    requires: ["calendar_id"],
  },
  {
    id: "GOOGLESUPER_CALENDARS_DELETE",
    label: "Delete Calendar",
    description: "Permanently delete a secondary calendar. Requires calendar_id.",
    group: "calendar",
    provides: [],
    requires: ["calendar_id"],
  },
  {
    id: "GOOGLESUPER_EVENTS_LIST",
    label: "List Events",
    description: "List events in a calendar. Requires calendar_id. Returns event_ids.",
    group: "calendar",
    provides: ["event_id"],
    requires: ["calendar_id"],
  },
  {
    id: "GOOGLESUPER_EVENTS_GET",
    label: "Get Event",
    description: "Retrieve full details of a calendar event. Requires calendar_id + event_id.",
    group: "calendar",
    provides: [],
    requires: ["calendar_id", "event_id"],
  },
  {
    id: "GOOGLESUPER_EVENTS_INSERT",
    label: "Create Event",
    description: "Create a new event in a calendar. Requires calendar_id.",
    group: "calendar",
    provides: ["event_id"],
    requires: ["calendar_id"],
  },
  {
    id: "GOOGLESUPER_EVENTS_UPDATE",
    label: "Update Event",
    description: "Update an existing calendar event. Requires calendar_id + event_id.",
    group: "calendar",
    provides: [],
    requires: ["calendar_id", "event_id"],
  },
  {
    id: "GOOGLESUPER_EVENTS_DELETE",
    label: "Delete Event",
    description: "Delete a calendar event. Requires calendar_id + event_id.",
    group: "calendar",
    provides: [],
    requires: ["calendar_id", "event_id"],
  },
  {
    id: "GOOGLESUPER_CLEAR_CALENDAR",
    label: "Clear Calendar",
    description: "Delete all events from a primary calendar. Requires calendar_id.",
    group: "calendar",
    provides: [],
    requires: ["calendar_id"],
  },
  {
    id: "GOOGLESUPER_ACL_LIST",
    label: "List ACL Rules",
    description: "List access control rules for a calendar. Requires calendar_id. Returns rule_ids.",
    group: "calendar",
    provides: ["rule_id"],
    requires: ["calendar_id"],
  },
  {
    id: "GOOGLESUPER_ACL_INSERT",
    label: "Create ACL Rule",
    description: "Grant sharing permission to a user/group/domain. Requires calendar_id.",
    group: "calendar",
    provides: ["rule_id"],
    requires: ["calendar_id"],
  },
  {
    id: "GOOGLESUPER_ACL_DELETE",
    label: "Delete ACL Rule",
    description: "Remove a sharing permission rule. Requires calendar_id + rule_id.",
    group: "calendar",
    provides: [],
    requires: ["calendar_id", "rule_id"],
  },
  {
    id: "GOOGLESUPER_ACL_UPDATE",
    label: "Update ACL Rule",
    description: "Fully update a calendar access rule. Requires calendar_id + rule_id.",
    group: "calendar",
    provides: [],
    requires: ["calendar_id", "rule_id"],
  },

  // ─── Drive ────────────────────────────────────────────────────────────────
  {
    id: "GOOGLESUPER_DRIVE_LIST_FILES",
    label: "List Files",
    description: "List files in Google Drive. Returns file_ids and metadata.",
    group: "drive",
    provides: ["file_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_DRIVE_SEARCH_FILES",
    label: "Search Files",
    description: "Search Drive files using query syntax. Returns matching file_ids.",
    group: "drive",
    provides: ["file_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_DRIVE_CREATE_FILE",
    label: "Create File",
    description: "Create a new file in Google Drive. Returns file_id.",
    group: "drive",
    provides: ["file_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_DRIVE_GET_FILE",
    label: "Get File Metadata",
    description: "Retrieve metadata for a specific Drive file. Requires file_id.",
    group: "drive",
    provides: [],
    requires: ["file_id"],
  },
  {
    id: "GOOGLESUPER_DRIVE_DELETE_FILE",
    label: "Delete File",
    description: "Permanently delete a Drive file. Requires file_id.",
    group: "drive",
    provides: [],
    requires: ["file_id"],
  },
  {
    id: "GOOGLESUPER_DRIVE_DOWNLOAD_FILE",
    label: "Download File",
    description: "Download file content from Drive. Requires file_id.",
    group: "drive",
    provides: [],
    requires: ["file_id"],
  },
  {
    id: "GOOGLESUPER_COPY_FILE_ADVANCED",
    label: "Copy File",
    description: "Duplicate a Drive file with advanced options. Requires file_id. Returns new file_id.",
    group: "drive",
    provides: ["file_id"],
    requires: ["file_id"],
  },
  {
    id: "GOOGLESUPER_CREATE_COMMENT",
    label: "Comment on File",
    description: "Add a comment to a Drive file. Requires file_id.",
    group: "drive",
    provides: [],
    requires: ["file_id"],
  },
  {
    id: "GOOGLESUPER_ADD_FILE_SHARING_PREFERENCE",
    label: "Share File",
    description: "Grant sharing permissions to a Drive file. Requires file_id.",
    group: "drive",
    provides: [],
    requires: ["file_id"],
  },
  {
    id: "GOOGLESUPER_DRIVE_LIST_FOLDERS",
    label: "List Folders",
    description: "List folders in Google Drive. Returns folder_ids.",
    group: "drive",
    provides: ["folder_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_ADD_PARENT",
    label: "Move to Folder",
    description: "Move a file into a folder (add parent). Requires file_id + folder_id.",
    group: "drive",
    provides: [],
    requires: ["file_id", "folder_id"],
  },

  // ─── Sheets ───────────────────────────────────────────────────────────────
  {
    id: "GOOGLESUPER_SHEETS_LIST_SPREADSHEETS",
    label: "List Spreadsheets",
    description: "List all Google Sheets spreadsheets in Drive. Returns spreadsheet_ids.",
    group: "sheets",
    provides: ["spreadsheet_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_SHEETS_CREATE_SPREADSHEET",
    label: "Create Spreadsheet",
    description: "Create a new Google Sheets spreadsheet. Returns spreadsheet_id.",
    group: "sheets",
    provides: ["spreadsheet_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_BATCH_GET",
    label: "Read Cell Ranges",
    description: "Read values from one or more cell ranges. Requires spreadsheet_id.",
    group: "sheets",
    provides: [],
    requires: ["spreadsheet_id"],
  },
  {
    id: "GOOGLESUPER_ADD_SHEET",
    label: "Add Sheet Tab",
    description: "Add a new sheet tab to a spreadsheet. Requires spreadsheet_id. Returns sheet_id.",
    group: "sheets",
    provides: ["sheet_id"],
    requires: ["spreadsheet_id"],
  },
  {
    id: "GOOGLESUPER_APPEND_DIMENSION",
    label: "Append Rows/Columns",
    description: "Add empty rows or columns to a sheet. Requires spreadsheet_id + sheet_id.",
    group: "sheets",
    provides: [],
    requires: ["spreadsheet_id", "sheet_id"],
  },
  {
    id: "GOOGLESUPER_CREATE_CHART",
    label: "Create Chart",
    description: "Create a chart from sheet data. Requires spreadsheet_id + sheet_id.",
    group: "sheets",
    provides: [],
    requires: ["spreadsheet_id", "sheet_id"],
  },
  {
    id: "GOOGLESUPER_CLEAR_VALUES",
    label: "Clear Cells",
    description: "Clear cell content from an A1-notation range. Requires spreadsheet_id.",
    group: "sheets",
    provides: [],
    requires: ["spreadsheet_id"],
  },
  {
    id: "GOOGLESUPER_BATCH_UPDATE",
    label: "Write Cells",
    description: "Write values to one or more cell ranges. Requires spreadsheet_id.",
    group: "sheets",
    provides: [],
    requires: ["spreadsheet_id"],
  },
  {
    id: "GOOGLESUPER_AGGREGATE_COLUMN_DATA",
    label: "Aggregate Column",
    description: "Perform sum/avg/count/min/max on filtered column data. Requires spreadsheet_id.",
    group: "sheets",
    provides: [],
    requires: ["spreadsheet_id"],
  },
  {
    id: "GOOGLESUPER_AUTO_RESIZE_DIMENSIONS",
    label: "Auto-Resize Columns",
    description: "Auto-fit column widths or row heights. Requires spreadsheet_id.",
    group: "sheets",
    provides: [],
    requires: ["spreadsheet_id"],
  },

  // ─── Tasks ────────────────────────────────────────────────────────────────
  {
    id: "GOOGLESUPER_TASKS_LIST_TASKLISTS",
    label: "List Task Lists",
    description: "List all Google Task Lists. Returns tasklist_ids.",
    group: "tasks",
    provides: ["tasklist_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_TASKS_CREATE_TASKLIST",
    label: "Create Task List",
    description: "Create a new Google Task List. Returns tasklist_id.",
    group: "tasks",
    provides: ["tasklist_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_TASKS_LIST_TASKS",
    label: "List Tasks",
    description: "List tasks in a task list. Requires tasklist_id. Returns task_ids.",
    group: "tasks",
    provides: ["task_id"],
    requires: ["tasklist_id"],
  },
  {
    id: "GOOGLESUPER_TASKS_GET_TASK",
    label: "Get Task",
    description: "Retrieve details of a specific task. Requires tasklist_id + task_id.",
    group: "tasks",
    provides: [],
    requires: ["tasklist_id", "task_id"],
  },
  {
    id: "GOOGLESUPER_TASKS_INSERT_TASK",
    label: "Create Task",
    description: "Create a new task in a task list. Requires tasklist_id.",
    group: "tasks",
    provides: ["task_id"],
    requires: ["tasklist_id"],
  },
  {
    id: "GOOGLESUPER_TASKS_UPDATE_TASK",
    label: "Update Task",
    description: "Update an existing task. Requires tasklist_id + task_id.",
    group: "tasks",
    provides: [],
    requires: ["tasklist_id", "task_id"],
  },
  {
    id: "GOOGLESUPER_TASKS_DELETE_TASK",
    label: "Delete Task",
    description: "Delete a task from a list. Requires tasklist_id + task_id.",
    group: "tasks",
    provides: [],
    requires: ["tasklist_id", "task_id"],
  },
  {
    id: "GOOGLESUPER_CLEAR_TASKS",
    label: "Clear Completed Tasks",
    description: "Remove all completed tasks from a list. Requires tasklist_id.",
    group: "tasks",
    provides: [],
    requires: ["tasklist_id"],
  },
  {
    id: "GOOGLESUPER_BULK_INSERT_TASKS",
    label: "Bulk Create Tasks",
    description: "Create multiple tasks efficiently. Requires tasklist_id.",
    group: "tasks",
    provides: [],
    requires: ["tasklist_id"],
  },

  // ─── Photos ───────────────────────────────────────────────────────────────
  {
    id: "GOOGLESUPER_PHOTOS_LIST_ALBUMS",
    label: "List Albums",
    description: "List all Google Photos albums. Returns album_ids.",
    group: "photos",
    provides: ["album_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_CREATE_ALBUM",
    label: "Create Album",
    description: "Create a new Google Photos album. Returns album_id.",
    group: "photos",
    provides: ["album_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_PHOTOS_LIST_MEDIA_ITEMS",
    label: "List Media Items",
    description: "List photos/videos from Google Photos. Returns media_item_ids.",
    group: "photos",
    provides: ["media_item_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_BATCH_CREATE_MEDIA_ITEMS",
    label: "Upload Media",
    description: "Upload and create multiple photos/videos. Returns media_item_ids.",
    group: "photos",
    provides: ["media_item_id"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_BATCH_ADD_MEDIA_ITEMS",
    label: "Add Media to Album",
    description: "Add up to 50 media items to an album. Requires album_id + media_item_ids.",
    group: "photos",
    provides: [],
    requires: ["album_id", "media_item_id"],
  },
  {
    id: "GOOGLESUPER_BATCH_GET_MEDIA_ITEMS",
    label: "Get Media Details",
    description: "Retrieve details for specified media items. Requires media_item_ids.",
    group: "photos",
    provides: [],
    requires: ["media_item_id"],
  },
  {
    id: "GOOGLESUPER_ADD_ENRICHMENT",
    label: "Add Album Enrichment",
    description: "Add text/location/map enrichment to an album. Requires album_id.",
    group: "photos",
    provides: [],
    requires: ["album_id"],
  },

  // ─── Analytics ────────────────────────────────────────────────────────────
  {
    id: "GOOGLESUPER_ANALYTICS_LIST_PROPERTIES",
    label: "List GA4 Properties",
    description: "List Google Analytics 4 properties. Returns property IDs.",
    group: "analytics",
    provides: ["ga4_property"],
    requires: [],
  },
  {
    id: "GOOGLESUPER_BATCH_RUN_REPORTS",
    label: "Run Analytics Reports",
    description: "Fetch up to 5 GA4 reports in a single request. Requires property ID.",
    group: "analytics",
    provides: [],
    requires: ["ga4_property"],
  },
  {
    id: "GOOGLESUPER_BATCH_RUN_PIVOT_REPORTS",
    label: "Run Pivot Reports",
    description: "Return multiple pivot table reports. Requires property ID.",
    group: "analytics",
    provides: [],
    requires: ["ga4_property"],
  },
  {
    id: "GOOGLESUPER_CREATE_CUSTOM_DIMENSION",
    label: "Create Custom Dimension",
    description: "Add a custom dimension to a GA4 property. Requires property ID. Returns dimension_name.",
    group: "analytics",
    provides: ["dimension_name"],
    requires: ["ga4_property"],
  },
  {
    id: "GOOGLESUPER_ARCHIVE_CUSTOM_DIMENSION",
    label: "Archive Custom Dimension",
    description: "Remove a custom dimension from active use. Requires dimension_name (with property path).",
    group: "analytics",
    provides: [],
    requires: ["dimension_name"],
  },

  // ─── GitHub: Repos ────────────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_REPOS_FOR_AUTH_USER",
    label: "List My Repos",
    description: "List repositories for the authenticated user. Returns owner + repo names.",
    group: "github_repo",
    provides: ["owner", "repo"],
    requires: [],
  },
  {
    id: "GITHUB_LIST_REPOS_FOR_ORG",
    label: "List Org Repos",
    description: "List repositories in an organization. Requires org name. Returns owner + repo.",
    group: "github_repo",
    provides: ["owner", "repo"],
    requires: ["org"],
  },
  {
    id: "GITHUB_CREATE_REPO",
    label: "Create Repo",
    description: "Create a new GitHub repository. Returns owner + repo.",
    group: "github_repo",
    provides: ["owner", "repo"],
    requires: [],
  },
  {
    id: "GITHUB_GET_REPO",
    label: "Get Repo",
    description: "Get full repository metadata. Requires owner + repo.",
    group: "github_repo",
    provides: [],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_DELETE_REPO",
    label: "Delete Repo",
    description: "Permanently delete a repository. Requires owner + repo.",
    group: "github_repo",
    provides: [],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_CREATE_FORK",
    label: "Fork Repo",
    description: "Fork a repository to another account. Requires owner + repo.",
    group: "github_repo",
    provides: [],
    requires: ["owner", "repo"],
  },

  // ─── GitHub: Branches ─────────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_BRANCHES",
    label: "List Branches",
    description: "List branches for a repository. Requires owner + repo. Returns branch_names.",
    group: "github_branches",
    provides: ["branch_name"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_CREATE_BRANCH",
    label: "Create Branch",
    description: "Create a new branch from a commit SHA. Requires owner + repo + sha.",
    group: "github_branches",
    provides: ["branch_name"],
    requires: ["owner", "repo", "commit_sha"],
  },

  // ─── GitHub: Commits ──────────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_COMMITS",
    label: "List Commits",
    description: "List commits for a repository. Requires owner + repo. Returns commit SHAs.",
    group: "github_commits",
    provides: ["commit_sha"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_GET_COMMIT",
    label: "Get Commit",
    description: "Fetch full details of a commit. Requires owner + repo + commit_sha.",
    group: "github_commits",
    provides: [],
    requires: ["owner", "repo", "commit_sha"],
  },
  {
    id: "GITHUB_COMPARE_TWO_COMMITS",
    label: "Compare Commits",
    description: "Compare two commits (diff). Requires owner + repo + two commit SHAs (BASE...HEAD format).",
    group: "github_commits",
    provides: [],
    requires: ["owner", "repo", "commit_sha"],
  },
  {
    id: "GITHUB_CREATE_A_BLOB",
    label: "Create Blob",
    description: "Create a Git blob object from file content. Requires owner + repo. Returns blob_sha.",
    group: "github_commits",
    provides: ["blob_sha"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_CREATE_A_TREE",
    label: "Create Tree",
    description: "Create a Git tree from blobs. Requires owner + repo + blob_sha. Returns tree_sha.",
    group: "github_commits",
    provides: ["tree_sha"],
    requires: ["owner", "repo", "blob_sha"],
  },
  {
    id: "GITHUB_CREATE_A_COMMIT",
    label: "Create Commit",
    description: "Create a Git commit from a tree + parent commit. Requires owner + repo + tree_sha + parent commit_sha. Returns new commit_sha.",
    group: "github_commits",
    provides: ["commit_sha"],
    requires: ["owner", "repo", "tree_sha", "commit_sha"],
  },
  {
    id: "GITHUB_COMMIT_MULTIPLE_FILES",
    label: "Commit Multiple Files",
    description: "Atomically create/update/delete files in one commit. Requires owner + repo + branch_name.",
    group: "github_commits",
    provides: [],
    requires: ["owner", "repo", "branch_name"],
  },
  {
    id: "GITHUB_CREATE_A_COMMIT_COMMENT",
    label: "Comment on Commit",
    description: "Add a comment to a specific commit. Requires owner + repo + commit_sha.",
    group: "github_commits",
    provides: [],
    requires: ["owner", "repo", "commit_sha"],
  },
  {
    id: "GITHUB_CREATE_A_COMMIT_STATUS",
    label: "Set Commit Status",
    description: "Set CI/CD status (pending/success/failure/error) on a commit. Requires owner + repo + commit_sha.",
    group: "github_commits",
    provides: [],
    requires: ["owner", "repo", "commit_sha"],
  },

  // ─── GitHub: Issues ───────────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_ISSUES",
    label: "List Issues",
    description: "List issues for a repository. Requires owner + repo. Returns issue_numbers.",
    group: "github_issues",
    provides: ["issue_number"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_GET_ISSUE",
    label: "Get Issue",
    description: "Retrieve full details of an issue. Requires owner + repo + issue_number.",
    group: "github_issues",
    provides: [],
    requires: ["owner", "repo", "issue_number"],
  },
  {
    id: "GITHUB_CREATE_ISSUE",
    label: "Create Issue",
    description: "Open a new issue in a repository. Requires owner + repo.",
    group: "github_issues",
    provides: ["issue_number"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_UPDATE_ISSUE",
    label: "Update Issue",
    description: "Edit an existing issue (title, body, state, etc.). Requires owner + repo + issue_number.",
    group: "github_issues",
    provides: [],
    requires: ["owner", "repo", "issue_number"],
  },
  {
    id: "GITHUB_ADD_ASSIGNEES_TO_AN_ISSUE",
    label: "Assign Users to Issue",
    description: "Assign up to 10 users to an issue. Requires owner + repo + issue_number.",
    group: "github_issues",
    provides: [],
    requires: ["owner", "repo", "issue_number"],
  },
  {
    id: "GITHUB_ADD_LABELS_TO_AN_ISSUE",
    label: "Add Labels to Issue",
    description: "Apply labels to an issue. Requires owner + repo + issue_number + label_names.",
    group: "github_issues",
    provides: [],
    requires: ["owner", "repo", "issue_number", "label_name"],
  },
  {
    id: "GITHUB_LIST_LABELS_FOR_REPO",
    label: "List Repo Labels",
    description: "List all labels in a repository. Requires owner + repo. Returns label_names.",
    group: "github_issues",
    provides: ["label_name"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_CREATE_LABEL",
    label: "Create Label",
    description: "Create a new label in a repository. Requires owner + repo. Returns label_name.",
    group: "github_issues",
    provides: ["label_name"],
    requires: ["owner", "repo"],
  },

  // ─── GitHub: Pull Requests ────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_PULL_REQUESTS",
    label: "List Pull Requests",
    description: "List open/closed PRs for a repository. Requires owner + repo. Returns pull_numbers.",
    group: "github_prs",
    provides: ["pull_number"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_GET_PULL_REQUEST",
    label: "Get Pull Request",
    description: "Retrieve full PR details. Requires owner + repo + pull_number.",
    group: "github_prs",
    provides: [],
    requires: ["owner", "repo", "pull_number"],
  },
  {
    id: "GITHUB_CREATE_PULL_REQUEST",
    label: "Create Pull Request",
    description: "Open a new pull request. Requires owner + repo + head branch + base branch.",
    group: "github_prs",
    provides: ["pull_number"],
    requires: ["owner", "repo", "branch_name"],
  },
  {
    id: "GITHUB_MERGE_PULL_REQUEST",
    label: "Merge Pull Request",
    description: "Merge a pull request. Requires owner + repo + pull_number.",
    group: "github_prs",
    provides: [],
    requires: ["owner", "repo", "pull_number"],
  },
  {
    id: "GITHUB_CHECK_IF_PULL_REQUEST_HAS_BEEN_MERGED",
    label: "Check PR Merged",
    description: "Check if a PR has been merged (HTTP 204 = merged). Requires owner + repo + pull_number.",
    group: "github_prs",
    provides: [],
    requires: ["owner", "repo", "pull_number"],
  },

  // ─── GitHub: Actions ──────────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_WORKFLOWS",
    label: "List Workflows",
    description: "List GitHub Actions workflows in a repository. Requires owner + repo. Returns workflow_ids.",
    group: "github_actions",
    provides: ["workflow_id"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_LIST_WORKFLOW_RUNS",
    label: "List Workflow Runs",
    description: "List recent workflow run history. Requires owner + repo. Returns run_ids.",
    group: "github_actions",
    provides: ["run_id"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_TRIGGER_WORKFLOW",
    label: "Trigger Workflow",
    description: "Manually trigger a workflow dispatch event. Requires owner + repo + workflow_id.",
    group: "github_actions",
    provides: [],
    requires: ["owner", "repo", "workflow_id"],
  },
  {
    id: "GITHUB_CANCEL_WORKFLOW_RUN",
    label: "Cancel Workflow Run",
    description: "Cancel a queued or in-progress workflow run. Requires owner + repo + run_id.",
    group: "github_actions",
    provides: [],
    requires: ["owner", "repo", "run_id"],
  },
  {
    id: "GITHUB_APPROVE_WORKFLOW_RUN_FOR_FORK_PULL_REQUEST",
    label: "Approve Fork Workflow",
    description: "Approve a workflow run from a fork PR. Requires owner + repo + run_id.",
    group: "github_actions",
    provides: [],
    requires: ["owner", "repo", "run_id"],
  },

  // ─── GitHub: Deployments ──────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_DEPLOYMENTS",
    label: "List Deployments",
    description: "List deployments for a repository. Requires owner + repo. Returns deployment_ids.",
    group: "github_deploy",
    provides: ["deployment_id"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_CREATE_DEPLOYMENT",
    label: "Create Deployment",
    description: "Create a deployment targeting a ref (branch, tag, SHA). Requires owner + repo + ref.",
    group: "github_deploy",
    provides: ["deployment_id"],
    requires: ["owner", "repo", "branch_name"],
  },
  {
    id: "GITHUB_CREATE_DEPLOYMENT_STATUS",
    label: "Update Deployment Status",
    description: "Update the operational state of a deployment. Requires owner + repo + deployment_id.",
    group: "github_deploy",
    provides: [],
    requires: ["owner", "repo", "deployment_id"],
  },

  // ─── GitHub: Releases ─────────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_RELEASES",
    label: "List Releases",
    description: "List releases for a repository. Requires owner + repo. Returns release_ids.",
    group: "github_releases",
    provides: ["release_id"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_GET_RELEASE",
    label: "Get Release",
    description: "Retrieve release details. Requires owner + repo + release_id.",
    group: "github_releases",
    provides: [],
    requires: ["owner", "repo", "release_id"],
  },
  {
    id: "GITHUB_CREATE_RELEASE",
    label: "Create Release",
    description: "Create a new release (with tag). Requires owner + repo.",
    group: "github_releases",
    provides: ["release_id"],
    requires: ["owner", "repo"],
  },

  // ─── GitHub: Org / Teams ──────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_ORGS_FOR_AUTH_USER",
    label: "List My Orgs",
    description: "List organizations for the authenticated user. Returns org names.",
    group: "github_org",
    provides: ["org"],
    requires: [],
  },
  {
    id: "GITHUB_LIST_TEAMS",
    label: "List Teams",
    description: "List teams in an organization. Requires org. Returns team_slugs.",
    group: "github_org",
    provides: ["team_slug"],
    requires: ["org"],
  },
  {
    id: "GITHUB_CREATE_TEAM",
    label: "Create Team",
    description: "Create a new team in an organization. Requires org. Returns team_slug.",
    group: "github_org",
    provides: ["team_slug"],
    requires: ["org"],
  },
  {
    id: "GITHUB_LIST_MEMBERS",
    label: "List Org Members",
    description: "List members of an organization. Requires org. Returns usernames.",
    group: "github_org",
    provides: ["username"],
    requires: ["org"],
  },
  {
    id: "GITHUB_ADD_OR_UPDATE_TEAM_MEMBERSHIP_FOR_USER",
    label: "Update Team Membership",
    description: "Add/update a user's membership in a team. Requires org + team_slug + username.",
    group: "github_org",
    provides: [],
    requires: ["org", "team_slug", "username"],
  },

  // ─── GitHub: Collaborators ────────────────────────────────────────────────
  {
    id: "GITHUB_LIST_COLLABORATORS",
    label: "List Collaborators",
    description: "List collaborators for a repository. Requires owner + repo. Returns usernames.",
    group: "github_collaborators",
    provides: ["username"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_ADD_A_REPOSITORY_COLLABORATOR",
    label: "Add Collaborator",
    description: "Grant user access to a repository. Requires owner + repo + username.",
    group: "github_collaborators",
    provides: [],
    requires: ["owner", "repo", "username"],
  },
  {
    id: "GITHUB_LIST_REPOSITORY_INVITATIONS",
    label: "List Repo Invitations",
    description: "List pending repository invitations. Requires owner + repo. Returns invitation_ids.",
    group: "github_collaborators",
    provides: ["invitation_id"],
    requires: ["owner", "repo"],
  },
  {
    id: "GITHUB_ACCEPT_REPOSITORY_INVITATION",
    label: "Accept Invitation",
    description: "Accept a repository collaboration invitation. Requires invitation_id.",
    group: "github_collaborators",
    provides: [],
    requires: ["invitation_id"],
  },

  // ─── GitHub: Checks ───────────────────────────────────────────────────────
  {
    id: "GITHUB_CREATE_A_CHECK_RUN",
    label: "Create Check Run",
    description: "Report CI check status with annotations. Requires owner + repo + commit_sha (head_sha).",
    group: "github_checks",
    provides: [],
    requires: ["owner", "repo", "commit_sha"],
  },
];

export const dependencies: DependencyEdge[] = [
  // ── Gmail ─────────────────────────────────────────────────────────────────
  { from: "GOOGLESUPER_GMAIL_LIST_THREADS",      to: "GOOGLESUPER_GMAIL_GET_THREAD",          parameter: "thread_id" },
  { from: "GOOGLESUPER_GMAIL_LIST_THREADS",      to: "GOOGLESUPER_GMAIL_REPLY_TO_THREAD",     parameter: "thread_id" },

  { from: "GOOGLESUPER_GMAIL_LIST_MESSAGES",     to: "GOOGLESUPER_GMAIL_GET_MESSAGE",         parameter: "message_id" },
  { from: "GOOGLESUPER_GMAIL_LIST_MESSAGES",     to: "GOOGLESUPER_GMAIL_DELETE_MESSAGE",      parameter: "message_id" },
  { from: "GOOGLESUPER_GMAIL_LIST_MESSAGES",     to: "GOOGLESUPER_ADD_LABEL_TO_EMAIL",        parameter: "message_id" },
  { from: "GOOGLESUPER_GMAIL_LIST_MESSAGES",     to: "GOOGLESUPER_BATCH_DELETE_MESSAGES",     parameter: "message_id" },
  { from: "GOOGLESUPER_GMAIL_LIST_MESSAGES",     to: "GOOGLESUPER_BATCH_MODIFY_MESSAGES",     parameter: "message_id" },

  { from: "GOOGLESUPER_GMAIL_LIST_LABELS",       to: "GOOGLESUPER_ADD_LABEL_TO_EMAIL",        parameter: "label_id" },
  { from: "GOOGLESUPER_GMAIL_LIST_LABELS",       to: "GOOGLESUPER_BATCH_MODIFY_MESSAGES",     parameter: "label_id" },
  { from: "GOOGLESUPER_GMAIL_CREATE_LABEL",      to: "GOOGLESUPER_ADD_LABEL_TO_EMAIL",        parameter: "label_id" },
  { from: "GOOGLESUPER_GMAIL_CREATE_LABEL",      to: "GOOGLESUPER_BATCH_MODIFY_MESSAGES",     parameter: "label_id" },

  { from: "GOOGLESUPER_GMAIL_LIST_DRAFTS",       to: "GOOGLESUPER_GMAIL_GET_DRAFT",           parameter: "draft_id" },
  { from: "GOOGLESUPER_GMAIL_LIST_DRAFTS",       to: "GOOGLESUPER_GMAIL_SEND_DRAFT",          parameter: "draft_id" },
  { from: "GOOGLESUPER_GMAIL_CREATE_DRAFT",      to: "GOOGLESUPER_GMAIL_GET_DRAFT",           parameter: "draft_id" },
  { from: "GOOGLESUPER_GMAIL_CREATE_DRAFT",      to: "GOOGLESUPER_GMAIL_SEND_DRAFT",          parameter: "draft_id" },

  { from: "GOOGLESUPER_CONTACTS_SEARCH",         to: "GOOGLESUPER_GMAIL_SEND_EMAIL",          parameter: "email" },
  { from: "GOOGLESUPER_CONTACTS_LIST",           to: "GOOGLESUPER_GMAIL_SEND_EMAIL",          parameter: "email" },

  // ── Calendar ──────────────────────────────────────────────────────────────
  { from: "GOOGLESUPER_CALENDAR_LIST_LIST",      to: "GOOGLESUPER_CALENDAR_LIST_GET",         parameter: "calendar_id" },
  { from: "GOOGLESUPER_CALENDAR_LIST_LIST",      to: "GOOGLESUPER_CALENDARS_UPDATE",          parameter: "calendar_id" },
  { from: "GOOGLESUPER_CALENDAR_LIST_LIST",      to: "GOOGLESUPER_CALENDARS_DELETE",          parameter: "calendar_id" },
  { from: "GOOGLESUPER_CALENDAR_LIST_LIST",      to: "GOOGLESUPER_EVENTS_LIST",               parameter: "calendar_id" },
  { from: "GOOGLESUPER_CALENDAR_LIST_LIST",      to: "GOOGLESUPER_EVENTS_INSERT",             parameter: "calendar_id" },
  { from: "GOOGLESUPER_CALENDAR_LIST_LIST",      to: "GOOGLESUPER_CLEAR_CALENDAR",            parameter: "calendar_id" },
  { from: "GOOGLESUPER_CALENDAR_LIST_LIST",      to: "GOOGLESUPER_ACL_LIST",                  parameter: "calendar_id" },
  { from: "GOOGLESUPER_CALENDAR_LIST_LIST",      to: "GOOGLESUPER_ACL_INSERT",                parameter: "calendar_id" },
  { from: "GOOGLESUPER_CALENDARS_INSERT",        to: "GOOGLESUPER_EVENTS_LIST",               parameter: "calendar_id" },
  { from: "GOOGLESUPER_CALENDARS_INSERT",        to: "GOOGLESUPER_EVENTS_INSERT",             parameter: "calendar_id" },

  { from: "GOOGLESUPER_EVENTS_LIST",             to: "GOOGLESUPER_EVENTS_GET",                parameter: "event_id" },
  { from: "GOOGLESUPER_EVENTS_LIST",             to: "GOOGLESUPER_EVENTS_UPDATE",             parameter: "event_id" },
  { from: "GOOGLESUPER_EVENTS_LIST",             to: "GOOGLESUPER_EVENTS_DELETE",             parameter: "event_id" },

  { from: "GOOGLESUPER_ACL_LIST",                to: "GOOGLESUPER_ACL_DELETE",                parameter: "rule_id" },
  { from: "GOOGLESUPER_ACL_LIST",                to: "GOOGLESUPER_ACL_UPDATE",                parameter: "rule_id" },

  // ── Drive ─────────────────────────────────────────────────────────────────
  { from: "GOOGLESUPER_DRIVE_LIST_FILES",        to: "GOOGLESUPER_DRIVE_GET_FILE",            parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_LIST_FILES",        to: "GOOGLESUPER_DRIVE_DELETE_FILE",         parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_LIST_FILES",        to: "GOOGLESUPER_DRIVE_DOWNLOAD_FILE",       parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_LIST_FILES",        to: "GOOGLESUPER_COPY_FILE_ADVANCED",        parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_LIST_FILES",        to: "GOOGLESUPER_CREATE_COMMENT",            parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_LIST_FILES",        to: "GOOGLESUPER_ADD_FILE_SHARING_PREFERENCE", parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_LIST_FILES",        to: "GOOGLESUPER_ADD_PARENT",                parameter: "file_id" },

  { from: "GOOGLESUPER_DRIVE_SEARCH_FILES",      to: "GOOGLESUPER_DRIVE_GET_FILE",            parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_SEARCH_FILES",      to: "GOOGLESUPER_DRIVE_DELETE_FILE",         parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_SEARCH_FILES",      to: "GOOGLESUPER_DRIVE_DOWNLOAD_FILE",       parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_SEARCH_FILES",      to: "GOOGLESUPER_ADD_FILE_SHARING_PREFERENCE", parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_SEARCH_FILES",      to: "GOOGLESUPER_CREATE_COMMENT",            parameter: "file_id" },

  { from: "GOOGLESUPER_DRIVE_CREATE_FILE",       to: "GOOGLESUPER_DRIVE_GET_FILE",            parameter: "file_id" },
  { from: "GOOGLESUPER_DRIVE_CREATE_FILE",       to: "GOOGLESUPER_ADD_FILE_SHARING_PREFERENCE", parameter: "file_id" },
  { from: "GOOGLESUPER_COPY_FILE_ADVANCED",      to: "GOOGLESUPER_ADD_FILE_SHARING_PREFERENCE", parameter: "file_id" },

  { from: "GOOGLESUPER_DRIVE_LIST_FOLDERS",      to: "GOOGLESUPER_ADD_PARENT",                parameter: "folder_id" },

  // ── Sheets ────────────────────────────────────────────────────────────────
  { from: "GOOGLESUPER_SHEETS_LIST_SPREADSHEETS", to: "GOOGLESUPER_BATCH_GET",               parameter: "spreadsheet_id" },
  { from: "GOOGLESUPER_SHEETS_LIST_SPREADSHEETS", to: "GOOGLESUPER_ADD_SHEET",               parameter: "spreadsheet_id" },
  { from: "GOOGLESUPER_SHEETS_LIST_SPREADSHEETS", to: "GOOGLESUPER_CLEAR_VALUES",            parameter: "spreadsheet_id" },
  { from: "GOOGLESUPER_SHEETS_LIST_SPREADSHEETS", to: "GOOGLESUPER_BATCH_UPDATE",            parameter: "spreadsheet_id" },
  { from: "GOOGLESUPER_SHEETS_LIST_SPREADSHEETS", to: "GOOGLESUPER_AGGREGATE_COLUMN_DATA",   parameter: "spreadsheet_id" },
  { from: "GOOGLESUPER_SHEETS_LIST_SPREADSHEETS", to: "GOOGLESUPER_AUTO_RESIZE_DIMENSIONS",  parameter: "spreadsheet_id" },
  { from: "GOOGLESUPER_SHEETS_CREATE_SPREADSHEET", to: "GOOGLESUPER_ADD_SHEET",             parameter: "spreadsheet_id" },
  { from: "GOOGLESUPER_SHEETS_CREATE_SPREADSHEET", to: "GOOGLESUPER_BATCH_GET",             parameter: "spreadsheet_id" },
  { from: "GOOGLESUPER_SHEETS_CREATE_SPREADSHEET", to: "GOOGLESUPER_BATCH_UPDATE",          parameter: "spreadsheet_id" },

  { from: "GOOGLESUPER_ADD_SHEET",               to: "GOOGLESUPER_APPEND_DIMENSION",          parameter: "sheet_id" },
  { from: "GOOGLESUPER_ADD_SHEET",               to: "GOOGLESUPER_CREATE_CHART",              parameter: "sheet_id" },

  // ── Tasks ─────────────────────────────────────────────────────────────────
  { from: "GOOGLESUPER_TASKS_LIST_TASKLISTS",    to: "GOOGLESUPER_TASKS_LIST_TASKS",          parameter: "tasklist_id" },
  { from: "GOOGLESUPER_TASKS_LIST_TASKLISTS",    to: "GOOGLESUPER_TASKS_INSERT_TASK",         parameter: "tasklist_id" },
  { from: "GOOGLESUPER_TASKS_LIST_TASKLISTS",    to: "GOOGLESUPER_CLEAR_TASKS",               parameter: "tasklist_id" },
  { from: "GOOGLESUPER_TASKS_LIST_TASKLISTS",    to: "GOOGLESUPER_BULK_INSERT_TASKS",         parameter: "tasklist_id" },
  { from: "GOOGLESUPER_TASKS_CREATE_TASKLIST",   to: "GOOGLESUPER_TASKS_LIST_TASKS",          parameter: "tasklist_id" },
  { from: "GOOGLESUPER_TASKS_CREATE_TASKLIST",   to: "GOOGLESUPER_TASKS_INSERT_TASK",         parameter: "tasklist_id" },

  { from: "GOOGLESUPER_TASKS_LIST_TASKS",        to: "GOOGLESUPER_TASKS_GET_TASK",            parameter: "task_id" },
  { from: "GOOGLESUPER_TASKS_LIST_TASKS",        to: "GOOGLESUPER_TASKS_UPDATE_TASK",         parameter: "task_id" },
  { from: "GOOGLESUPER_TASKS_LIST_TASKS",        to: "GOOGLESUPER_TASKS_DELETE_TASK",         parameter: "task_id" },

  // ── Photos ────────────────────────────────────────────────────────────────
  { from: "GOOGLESUPER_PHOTOS_LIST_ALBUMS",      to: "GOOGLESUPER_BATCH_ADD_MEDIA_ITEMS",     parameter: "album_id" },
  { from: "GOOGLESUPER_PHOTOS_LIST_ALBUMS",      to: "GOOGLESUPER_ADD_ENRICHMENT",            parameter: "album_id" },
  { from: "GOOGLESUPER_CREATE_ALBUM",            to: "GOOGLESUPER_BATCH_ADD_MEDIA_ITEMS",     parameter: "album_id" },
  { from: "GOOGLESUPER_CREATE_ALBUM",            to: "GOOGLESUPER_ADD_ENRICHMENT",            parameter: "album_id" },

  { from: "GOOGLESUPER_PHOTOS_LIST_MEDIA_ITEMS", to: "GOOGLESUPER_BATCH_ADD_MEDIA_ITEMS",    parameter: "media_item_id" },
  { from: "GOOGLESUPER_PHOTOS_LIST_MEDIA_ITEMS", to: "GOOGLESUPER_BATCH_GET_MEDIA_ITEMS",    parameter: "media_item_id" },
  { from: "GOOGLESUPER_BATCH_CREATE_MEDIA_ITEMS", to: "GOOGLESUPER_BATCH_ADD_MEDIA_ITEMS",   parameter: "media_item_id" },
  { from: "GOOGLESUPER_BATCH_CREATE_MEDIA_ITEMS", to: "GOOGLESUPER_BATCH_GET_MEDIA_ITEMS",   parameter: "media_item_id" },

  // ── Analytics ─────────────────────────────────────────────────────────────
  { from: "GOOGLESUPER_ANALYTICS_LIST_PROPERTIES", to: "GOOGLESUPER_BATCH_RUN_REPORTS",      parameter: "ga4_property" },
  { from: "GOOGLESUPER_ANALYTICS_LIST_PROPERTIES", to: "GOOGLESUPER_BATCH_RUN_PIVOT_REPORTS", parameter: "ga4_property" },
  { from: "GOOGLESUPER_ANALYTICS_LIST_PROPERTIES", to: "GOOGLESUPER_CREATE_CUSTOM_DIMENSION", parameter: "ga4_property" },
  { from: "GOOGLESUPER_CREATE_CUSTOM_DIMENSION",   to: "GOOGLESUPER_ARCHIVE_CUSTOM_DIMENSION", parameter: "dimension_name" },

  // ── GitHub: repo → list tools ─────────────────────────────────────────────
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_GET_REPO",                       parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_DELETE_REPO",                    parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_CREATE_FORK",                    parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_BRANCHES",                  parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_COMMITS",                   parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_ISSUES",                    parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_CREATE_ISSUE",                   parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_PULL_REQUESTS",             parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_LABELS_FOR_REPO",           parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_CREATE_LABEL",                   parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_WORKFLOWS",                 parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_WORKFLOW_RUNS",             parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_DEPLOYMENTS",               parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_RELEASES",                  parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_CREATE_RELEASE",                 parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_CREATE_A_BLOB",                  parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_COLLABORATORS",             parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_ADD_A_REPOSITORY_COLLABORATOR",  parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_AUTH_USER",     to: "GITHUB_LIST_REPOSITORY_INVITATIONS",    parameter: "owner/repo" },
  { from: "GITHUB_CREATE_REPO",                  to: "GITHUB_LIST_BRANCHES",                  parameter: "owner/repo" },
  { from: "GITHUB_CREATE_REPO",                  to: "GITHUB_LIST_COMMITS",                   parameter: "owner/repo" },
  { from: "GITHUB_CREATE_REPO",                  to: "GITHUB_CREATE_ISSUE",                   parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_ORG",           to: "GITHUB_LIST_BRANCHES",                  parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_ORG",           to: "GITHUB_LIST_COMMITS",                   parameter: "owner/repo" },
  { from: "GITHUB_LIST_REPOS_FOR_ORG",           to: "GITHUB_LIST_ISSUES",                    parameter: "owner/repo" },

  // ── GitHub: org → repos ───────────────────────────────────────────────────
  { from: "GITHUB_LIST_ORGS_FOR_AUTH_USER",      to: "GITHUB_LIST_REPOS_FOR_ORG",             parameter: "org" },
  { from: "GITHUB_LIST_ORGS_FOR_AUTH_USER",      to: "GITHUB_LIST_TEAMS",                     parameter: "org" },
  { from: "GITHUB_LIST_ORGS_FOR_AUTH_USER",      to: "GITHUB_CREATE_TEAM",                    parameter: "org" },
  { from: "GITHUB_LIST_ORGS_FOR_AUTH_USER",      to: "GITHUB_LIST_MEMBERS",                   parameter: "org" },

  // ── GitHub: branches ──────────────────────────────────────────────────────
  { from: "GITHUB_LIST_BRANCHES",                to: "GITHUB_CREATE_PULL_REQUEST",             parameter: "branch_name" },
  { from: "GITHUB_LIST_BRANCHES",                to: "GITHUB_COMMIT_MULTIPLE_FILES",           parameter: "branch_name" },
  { from: "GITHUB_LIST_BRANCHES",                to: "GITHUB_CREATE_DEPLOYMENT",               parameter: "branch_name" },

  // ── GitHub: commits ───────────────────────────────────────────────────────
  { from: "GITHUB_LIST_COMMITS",                 to: "GITHUB_GET_COMMIT",                      parameter: "commit_sha" },
  { from: "GITHUB_LIST_COMMITS",                 to: "GITHUB_COMPARE_TWO_COMMITS",             parameter: "commit_sha" },
  { from: "GITHUB_LIST_COMMITS",                 to: "GITHUB_CREATE_A_COMMIT_COMMENT",         parameter: "commit_sha" },
  { from: "GITHUB_LIST_COMMITS",                 to: "GITHUB_CREATE_A_COMMIT_STATUS",          parameter: "commit_sha" },
  { from: "GITHUB_LIST_COMMITS",                 to: "GITHUB_CREATE_A_CHECK_RUN",              parameter: "commit_sha" },
  { from: "GITHUB_LIST_COMMITS",                 to: "GITHUB_CREATE_A_COMMIT",                 parameter: "commit_sha" },
  { from: "GITHUB_LIST_COMMITS",                 to: "GITHUB_CREATE_BRANCH",                   parameter: "commit_sha" },

  { from: "GITHUB_CREATE_A_BLOB",               to: "GITHUB_CREATE_A_TREE",                   parameter: "blob_sha" },
  { from: "GITHUB_CREATE_A_TREE",               to: "GITHUB_CREATE_A_COMMIT",                 parameter: "tree_sha" },
  { from: "GITHUB_CREATE_A_COMMIT",             to: "GITHUB_CREATE_BRANCH",                   parameter: "commit_sha" },
  { from: "GITHUB_CREATE_A_COMMIT",             to: "GITHUB_CREATE_DEPLOYMENT",               parameter: "commit_sha" },

  // ── GitHub: issues ────────────────────────────────────────────────────────
  { from: "GITHUB_LIST_ISSUES",                  to: "GITHUB_GET_ISSUE",                       parameter: "issue_number" },
  { from: "GITHUB_LIST_ISSUES",                  to: "GITHUB_UPDATE_ISSUE",                    parameter: "issue_number" },
  { from: "GITHUB_LIST_ISSUES",                  to: "GITHUB_ADD_ASSIGNEES_TO_AN_ISSUE",       parameter: "issue_number" },
  { from: "GITHUB_LIST_ISSUES",                  to: "GITHUB_ADD_LABELS_TO_AN_ISSUE",          parameter: "issue_number" },

  { from: "GITHUB_LIST_LABELS_FOR_REPO",         to: "GITHUB_ADD_LABELS_TO_AN_ISSUE",          parameter: "label_name" },
  { from: "GITHUB_CREATE_LABEL",                 to: "GITHUB_ADD_LABELS_TO_AN_ISSUE",          parameter: "label_name" },

  // ── GitHub: PRs ───────────────────────────────────────────────────────────
  { from: "GITHUB_LIST_PULL_REQUESTS",           to: "GITHUB_GET_PULL_REQUEST",                parameter: "pull_number" },
  { from: "GITHUB_LIST_PULL_REQUESTS",           to: "GITHUB_MERGE_PULL_REQUEST",              parameter: "pull_number" },
  { from: "GITHUB_LIST_PULL_REQUESTS",           to: "GITHUB_CHECK_IF_PULL_REQUEST_HAS_BEEN_MERGED", parameter: "pull_number" },
  { from: "GITHUB_CREATE_PULL_REQUEST",          to: "GITHUB_MERGE_PULL_REQUEST",              parameter: "pull_number" },

  // ── GitHub: actions ───────────────────────────────────────────────────────
  { from: "GITHUB_LIST_WORKFLOWS",               to: "GITHUB_TRIGGER_WORKFLOW",                parameter: "workflow_id" },
  { from: "GITHUB_LIST_WORKFLOW_RUNS",           to: "GITHUB_CANCEL_WORKFLOW_RUN",             parameter: "run_id" },
  { from: "GITHUB_LIST_WORKFLOW_RUNS",           to: "GITHUB_APPROVE_WORKFLOW_RUN_FOR_FORK_PULL_REQUEST", parameter: "run_id" },

  // ── GitHub: deployments ───────────────────────────────────────────────────
  { from: "GITHUB_LIST_DEPLOYMENTS",             to: "GITHUB_CREATE_DEPLOYMENT_STATUS",        parameter: "deployment_id" },
  { from: "GITHUB_CREATE_DEPLOYMENT",            to: "GITHUB_CREATE_DEPLOYMENT_STATUS",        parameter: "deployment_id" },

  // ── GitHub: releases ──────────────────────────────────────────────────────
  { from: "GITHUB_LIST_RELEASES",                to: "GITHUB_GET_RELEASE",                     parameter: "release_id" },

  // ── GitHub: teams / org membership ───────────────────────────────────────
  { from: "GITHUB_LIST_TEAMS",                   to: "GITHUB_ADD_OR_UPDATE_TEAM_MEMBERSHIP_FOR_USER", parameter: "team_slug" },
  { from: "GITHUB_CREATE_TEAM",                  to: "GITHUB_ADD_OR_UPDATE_TEAM_MEMBERSHIP_FOR_USER", parameter: "team_slug" },
  { from: "GITHUB_LIST_MEMBERS",                 to: "GITHUB_ADD_OR_UPDATE_TEAM_MEMBERSHIP_FOR_USER", parameter: "username" },
  { from: "GITHUB_LIST_MEMBERS",                 to: "GITHUB_ADD_A_REPOSITORY_COLLABORATOR",   parameter: "username" },
  { from: "GITHUB_LIST_COLLABORATORS",           to: "GITHUB_ADD_A_REPOSITORY_COLLABORATOR",   parameter: "username" },

  // ── GitHub: invitations ───────────────────────────────────────────────────
  { from: "GITHUB_LIST_REPOSITORY_INVITATIONS",  to: "GITHUB_ACCEPT_REPOSITORY_INVITATION",    parameter: "invitation_id" },
];
